# -*- coding: utf-8 -*-
# SPDX-FileCopyrightText: : 2017-2023 The PyPSA-Eur Authors
#
# SPDX-License-Identifier: MIT

# This file is used to define the scenarios that are run by snakemake. Each entry on the first level is a scenario. Each scenario can contain configuration overrides with respect to the config/config.yaml settings.
#
# Example
#
# custom-scenario: # name of the scenario
#   electricity:
#       renewable_carriers: [wind, solar] # override the list of renewable carriers

lineexpansion:
  sector:
    ll: v1.2

base:
  scenario:
    ll:
    - v1.0

no-flex:
  sector:
    bev_dsm: false
    v2g: false
  solving:
    solver:
      name: gurobi
      options: gurobi-numeric-focus


flex:
  sector:
    bev_dsm: true
    v2g: false
  # clustering:
  #   temporal:
  #     resolution_elec: false
  #     resolution_sector: 25sn
  solving:
    solver:
      name: gurobi
      options: gurobi-numeric-focus


high-demand:
  sector:
    aviation_demand_factor:
      2020: 1.04
      2025: 1.3
      2030: 1.6
      2035: 1.9
      2040: 2.2
      2045: 2.5
      2050: 2.8

    vary_demand:
      land transport demand heavy:
        2020: 1.0
        2025: 1.3 # compared to 2015 from Eurostat
        2030: 1.4
        2035: 1.5
        2040: 1.6
        2045: 1.7
        2050: 1.8
      land transport demand light:
        2020: 1.0
        2025: 1.3 # compared to 2015 from Eurostat
        2030: 1.4
        2035: 1.5
        2040: 1.6
        2045: 1.7
        2050: 1.8

low-demand:
  sector:
    aviation_demand_factor:
      2020: 1.0
      2025: 1.0
      2030: 0.9
      2035: 0.9
      2040: 0.9
      2045: 0.8
      2050: 0.8

    vary_demand:
      land transport demand heavy:
        2020: 1.0
        2025: 1.0 # compared to 2015 from Eurostat
        2030: 1.0
        2035: 1.0
        2040: 1.0
        2045: 1.0
        2050: 1.0
      land transport demand light:
        2020: 0.9
        2025: 0.9 # compared to 2015 from Eurostat
        2030: 0.9
        2035: 0.9
        2040: 0.9
        2045: 0.9
        2050: 0.9


high-elec-eff:
  sector:
    transport_electric_efficiency:
      light: 80
      # assume 40 kWh/100 km = 0.04 MWh/100 km
      heavy: 40

high-h2-eff:
  # https://h2-mobility.de/wp-content/uploads/2021/02/H2M_Flottenpapier_English_20180822.pdf
  # assume in average 1kg_H2 per 100 km -> 1kg_H2 = 33 kWh_H2 (LHV)
  # 1 MWh_H2 = 30.003 100km
  # light: 30.003
  # assume 8.5 kg_H2 per 100 km -> 0.2805 MWh_H2 per 100 km
  # heavy: 3.565
  sector:
    transport_fuel_cell_efficiency:
      # 0.6 kg_H2 per 100 km -> 1 MWh = 1000 kWh = 30.3 kg_H2
      # 30.3 kg_H2 / 0.6 kg_H2/100 km = 50.5 per 100 km
      light: 50
      heavy: 10

high-h2-eff-extreme:
  # https://h2-mobility.de/wp-content/uploads/2021/02/H2M_Flottenpapier_English_20180822.pdf
  # assume in average 1kg_H2 per 100 km -> 1kg_H2 = 33 kWh_H2 (LHV)
  # 1 MWh_H2 = 30.003 100km
  # light: 30.003
  # assume 8.5 kg_H2 per 100 km -> 0.2805 MWh_H2 per 100 km
  # heavy: 3.565
  sector:
    transport_fuel_cell_efficiency:
      # 0.4 kg_H2 per 100 km -> 1 MWh = 1000 kWh = 30.3 kg_H2
      # 30.3 kg_H2 / 0.4 kg_H2/100 km = 76 per 100 km
      light: 76
      heavy: 20

high-electrolysis:
  sector:
    vary:
      capital_cost:
        H2 Electrolysis: 1.5

high-electrolysis-2:
  sector:
    vary:
      capital_cost:
        H2 Electrolysis: 2.5

low-electrolysis:
  sector:
    vary:
      capital_cost:
        H2 Electrolysis: 0.5


slow-transition:
  sector:
    vary:
      capital_cost:
        H2 Electrolysis: 1.0
      lifetime:
        land transport oil light: 2
        land transport oil heavy: 2
  # solving:
  #   solver:
  #     name: gurobi
  #     options: gurobi-numeric-focus
  # clustering:
  #   temporal:
  #     resolution_elec: false
  #     resolution_sector: 25sn

elec-optimist:
  sector:
    vary:
      capital_cost:
        land transport fuel cell light: 1.4
        land transport fuel cell heavy: 1.4
        land transport EV heavy: 0.6
        land transport EV light: 0.6

h2-optimist:
  sector:
    vary:
      capital_cost:
        land transport fuel cell light: 0.5
        land transport fuel cell heavy: 0.5
        land transport EV heavy: 1.5
        land transport EV light: 1.5


high-co2-seq:
  sector:
    co2_sequestration_potential: 600

high-co2-seq-1000:
  sector:
    co2_sequestration_potential: 1000
